### ISSUE TITLE
Insert Octave Session gives me "busy... Message"

### ISSUE THREAD

**Issue by BillyPocketNC** [texmacs/octave#22]
I am getting a busy message when I insert an octave session
![image](https://user-images.githubusercontent.com/48296685/124188271-46967f00-da7c-11eb-9acb-141e144f697e.png)
I am running octave 6.2.0 on windows 10

**Comment by da-liii** [comment]
Caused by #4 and Fixed by https://github.com/texmacs/octave/commit/54e3f46c1c3c5de49c432972867b6bb96fa13936
